version: "3.8"

services:
  nginx:
    depends_on:
      - client
    restart: always
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./html/:/var/www/html
      - /etc/letsencrypt/:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  client:
    stdin_open: true
    image: ghcr.io/camhungh/
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
