version: "3.8"

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/var/www/html
      - /etc/letsencrypt/:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
