server {
  server_name www.nikehotay.com nikehotay.com;

  location ~ /.well-known/acme-challenge {
    allow all;
    root /var/www/html;
  }

  root /var/www/html;

  location / {
   try_files $uri $uri/ =404;
  }

  location ~*  \.(jpg|jpeg|png|gif|ico|css|js|svg|webp|mp4|mind)$ {
    expires max;
  }

  listen 80;
  listen [::]:80;
}